--!Temos de verificar a ordem, para inserir as coisas
-- Criar Veiculos
into Carros values ('71 JN 41', 3, 'Aquamarine');
into Carros values ('39 BX 07', 4, 'Blue');
into Carros values ('60 ZE 61', 6, 'Blue');
into Carros values ('96 TX 19', 3, 'Puce');
into Carros values ('79 RA 02', 3, 'Violet');
into Carros values ('48 NC 11', 5, 'Puce');
into Carros values ('09 FE 76', 5, 'Pink');
into Carros values ('71 JM 20', 4, 'Orange');
into Carros values ('27 HM 72', 4, 'Khaki');
into Carros values ('31 CL 35', 6, 'Pink');
into Carros values ('05 PM 84', 5, 'Khaki');
into Carros values ('59 LK 49', 6, 'Aquamarine');
into Carros values ('53 TA 70', 4, 'Purple');
into Carros values ('20 LG 23', 5, 'Puce');
into Carros values ('65 UM 66', 6, 'Orange');
into Carros values ('46 YL 33', 6, 'Fuscia');
into Carros values ('68 BH 44', 4, 'Pink');
into Carros values ('15 RM 05', 5, 'Blue');
into Carros values ('42 RT 72', 6, 'Indigo');
into Carros values ('04 RB 33', 3, 'Green');
into Carros values ('26 ZF 17', 5, 'Green');
into Carros values ('21 KJ 40', 5, 'Maroon');
into Carros values ('82 RH 91', 5, 'Purple');
into Carros values ('80 HU 24', 3, 'Khaki');
into Carros values ('75 KD 21', 3, 'Indigo');
into Carros values ('35 KW 58', 6, 'Goldenrod');
into Carros values ('84 NC 01', 3, 'Violet');
into Carros values ('71 CH 90', 4, 'Teal');
into Carros values ('77 YP 92', 4, 'Aquamarine');
into Carros values ('15 JW 32', 3, 'Teal');
into Carros values ('66 BC 27', 3, 'Aquamarine');
into Carros values ('42 SS 81', 3, 'Red');
into Carros values ('97 AT 11', 6, 'Maroon');
into Carros values ('35 XT 61', 3, 'Pink');
into Carros values ('87 RL 59', 3, 'Puce');
into Carros values ('12 PF 28', 6, 'Mauv');
into Carros values ('82 AA 26', 6, 'Crimson');
into Carros values ('07 KV 88', 5, 'Aquamarine');
into Carros values ('24 QK 31', 5, 'Red');
into Carros values ('96 GG 74', 5, 'Indigo');
into Carros values ('87 IJ 45', 4, 'Crimson');
into Carros values ('31 XZ 22', 4, 'Aquamarine');
into Carros values ('82 SG 75', 4, 'Orange');
into Carros values ('87 NX 72', 3, 'Crimson');
into Carros values ('95 JV 12', 5, 'Khaki');
into Carros values ('28 NP 34', 3, 'Crimson');
into Carros values ('31 PB 88', 3, 'Green');
into Carros values ('13 ML 89', 5, 'Maroon');
into Carros values ('26 HQ 06', 6, 'Fuscia');
into Carros values ('26 RE 80', 3, 'Turquoise');
into Carros values ('44 IE 26', 4, 'Orange');
into Carros values ('52 GT 87', 5, 'Green');
into Carros values ('29 NV 13', 5, 'Green');
into Carros values ('73 CQ 38', 4, 'Fuscia');
into Carros values ('82 HN 20', 5, 'Mauv');
into Carros values ('38 QB 31', 3, 'Green');
into Carros values ('12 FD 76', 4, 'Goldenrod');
into Carros values ('72 KF 90', 4, 'Orange');
into Carros values ('48 DT 02', 3, 'Aquamarine');
into Carros values ('59 UR 72', 6, 'Indigo');
into Carros values ('12 ZD 73', 6, 'Purple');
into Carros values ('59 FH 89', 5, 'Turquoise');
into Carros values ('89 VW 20', 5, 'Maroon');
into Carros values ('99 XS 38', 4, 'Goldenrod');
into Carros values ('47 SO 79', 4, 'Turquoise');
into Carros values ('44 TI 68', 4, 'Puce');
into Carros values ('44 II 79', 6, 'Orange');
into Carros values ('01 OS 75', 3, 'Blue');
into Carros values ('59 RV 13', 6, 'Purple');
into Carros values ('17 VG 85', 3, 'Yellow');
into Carros values ('06 DO 26', 3, 'Mauv');
into Carros values ('25 IU 99', 5, 'Aquamarine');
into Carros values ('27 LG 66', 5, 'Green');
into Carros values ('10 MK 60', 3, 'Khaki');
into Carros values ('06 KL 24', 4, 'Yellow');
into Carros values ('27 MB 71', 5, 'Indigo');
into Carros values ('69 MY 78', 5, 'Fuscia');
into Carros values ('21 GJ 99', 6, 'Teal');
into Carros values ('82 DK 89', 3, 'Pink');
into Carros values ('58 LJ 14', 4, 'Crimson');
into Carros values ('16 MT 98', 3, 'Puce');
into Carros values ('81 OF 88', 5, 'Maroon');
into Carros values ('80 FB 10', 5, 'Turquoise');
into Carros values ('98 UJ 60', 3, 'Violet');
into Carros values ('20 CZ 12', 6, 'Aquamarine');
into Carros values ('64 MZ 92', 5, 'Aquamarine');
into Carros values ('21 JF 13', 6, 'Puce');
into Carros values ('32 VG 38', 6, 'Turquoise');
into Carros values ('86 OE 10', 3, 'Aquamarine');
into Carros values ('40 GE 82', 5, 'Green');
into Carros values ('36 BR 82', 5, 'Indigo');
into Carros values ('72 GA 50', 3, 'Blue');
into Carros values ('89 CL 79', 5, 'Aquamarine');
into Carros values ('74 XS 81', 5, 'Crimson');
into Carros values ('69 HC 72', 3, 'Maroon');
into Carros values ('54 LO 77', 4, 'Maroon');
into Carros values ('38 CH 92', 4, 'Crimson');
into Carros values ('31 NH 32', 5, 'Indigo');
into Carros values ('68 UO 24', 4, 'Blue');
into Carros values ('97 GR 75', 6, 'Teal');

--Criar Veiculos (Correspondentes a carros)
into Veiculos values ("71 JN 41","RDX","Acura");
into Veiculos values ("39 BX 07","Bronco","Ford");
into Veiculos values ("60 ZE 61","Outback","Subaru");
into Veiculos values ("96 TX 19","Villager","Mercury");
into Veiculos values ("79 RA 02","HHR","Chevrolet");
into Veiculos values ("48 NC 11","Town Car","Lincoln");
into Veiculos values ("09 FE 76","C-Class","Mercedes-Benz");
into Veiculos values ("71 JM 20","Grand Am","Pontiac");
into Veiculos values ("27 HM 72","Grand Cherokee","Jeep");
into Veiculos values ("31 CL 35","MX-3","Mazda");
into Veiculos values ("05 PM 84","Corrado","Volkswagen");
into Veiculos values ("59 LK 49","Carens","Kia");
into Veiculos values ("53 TA 70","Neon","Dodge");
into Veiculos values ("20 LG 23","GT-R","Nissan");
into Veiculos values ("65 UM 66","EXP","Ford");
into Veiculos values ("46 YL 33","Crown Victoria","Ford");
into Veiculos values ("68 BH 44","Neon","Dodge");
into Veiculos values ("15 RM 05","599 GTB Fiorano","Ferrari");
into Veiculos values ("42 RT 72","Yukon","GMC");
into Veiculos values ("04 RB 33","Nubira","Daewoo");
into Veiculos values ("26 ZF 17","Silverado Hybrid","Chevrolet");
into Veiculos values ("21 KJ 40","Bronco","Ford");
into Veiculos values ("82 RH 91","Ram Wagon B350","Dodge");
into Veiculos values ("80 HU 24","Neon","Dodge");
into Veiculos values ("75 KD 21","Grand Am","Pontiac");
into Veiculos values ("35 KW 58","Corrado","Volkswagen");
into Veiculos values ("84 NC 01","FJ Cruiser","Toyota");
into Veiculos values ("71 CH 90","Q","Infiniti");
into Veiculos values ("77 YP 92","Crown Victoria","Ford");
into Veiculos values ("15 JW 32","Transit Connect","Ford");
into Veiculos values ("66 BC 27","Aveo","Chevrolet");
into Veiculos values ("42 SS 81","RDX","Acura");
into Veiculos values ("97 AT 11","Neon","Dodge");
into Veiculos values ("35 XT 61","RDX","Acura");
into Veiculos values ("87 RL 59","Escalade EXT","Cadillac");
into Veiculos values ("12 PF 28","Caliber","Dodge");
into Veiculos values ("82 AA 26","F350","Ford");
into Veiculos values ("07 KV 88","Concorde","Chrysler");
into Veiculos values ("24 QK 31","RDX","Acura");
into Veiculos values ("96 GG 74","Outback","Subaru");
into Veiculos values ("87 IJ 45","F350","Ford");
into Veiculos values ("31 XZ 22","Caliber","Dodge");
into Veiculos values ("82 SG 75","Crown Victoria","Ford");
into Veiculos values ("87 NX 72","Ram Wagon B350","Dodge");
into Veiculos values ("95 JV 12","Bronco","Ford");
into Veiculos values ("28 NP 34","Pajero","Mitsubishi");
into Veiculos values ("31 PB 88","GS","Lexus");
into Veiculos values ("13 ML 89","Q","Infiniti");
into Veiculos values ("26 HQ 06","rio","Volkswagen");
into Veiculos values ("26 RE 80","Aveo","Chevrolet");
into Veiculos values ("44 IE 26","Navigator L","Lincoln");
into Veiculos values ("52 GT 87","Ram Wagon B350","Dodge");
into Veiculos values ("29 NV 13","Pajero","Mitsubishi");
into Veiculos values ("73 CQ 38","C-Class","Mercedes-Benz");
into Veiculos values ("82 HN 20","Navigator L","Lincoln");
into Veiculos values ("38 QB 31","Neon","Dodge");
into Veiculos values ("12 FD 76","Sierra 3500HD","GMC");
into Veiculos values ("72 KF 90","Ram Wagon B350","Dodge");
into Veiculos values ("48 DT 02","Bronco","Ford");
into Veiculos values ("59 UR 72","Interceptor","Jensen");
into Veiculos values ("12 ZD 73","MKS","Lincoln");
into Veiculos values ("59 FH 89","Forester","Subaru");
into Veiculos values ("89 VW 20","C-Class","Mercedes-Benz");
into Veiculos values ("99 XS 38","9-4X","Saab");
into Veiculos values ("47 SO 79","Nubira","Daewoo");
into Veiculos values ("44 TI 68","MX-3","Mazda");
into Veiculos values ("44 II 79","9-4X","Saab");
into Veiculos values ("01 OS 75","GS","Lexus");
into Veiculos values ("59 RV 13","MKS","Lincoln");
into Veiculos values ("17 VG 85","EXP","Ford");
into Veiculos values ("06 DO 26","GS","Lexus");
into Veiculos values ("25 IU 99","FJ Cruiser","Toyota");
into Veiculos values ("27 LG 66","EXP","Ford");
into Veiculos values ("10 MK 60","Transit Connect","Ford");
into Veiculos values ("06 KL 24","EXP","Ford");
into Veiculos values ("27 MB 71","Insight","Honda");
into Veiculos values ("69 MY 78","Bronco","Ford");
into Veiculos values ("21 GJ 99","Pajero","Mitsubishi");
into Veiculos values ("82 DK 89","GT-R","Nissan");
into Veiculos values ("58 LJ 14","GT-R","Nissan");
into Veiculos values ("16 MT 98","GT-R","Nissan");
into Veiculos values ("81 OF 88","Grand Cherokee","Jeep");
into Veiculos values ("80 FB 10","Corvette","Chevrolet");
into Veiculos values ("98 UJ 60","MX-3","Mazda");
into Veiculos values ("20 CZ 12","Silverado Hybrid","Chevrolet");
into Veiculos values ("64 MZ 92","Sierra 3500HD","GMC");
into Veiculos values ("21 JF 13","GS","Lexus");
into Veiculos values ("32 VG 38","Bronco","Ford");
into Veiculos values ("86 OE 10","Forester","Subaru");
into Veiculos values ("40 GE 82","Silverado Hybrid","Chevrolet");
into Veiculos values ("36 BR 82","Corvette","Chevrolet");
into Veiculos values ("72 GA 50","Grand Am","Pontiac");
into Veiculos values ("89 CL 79","Pajero","Mitsubishi");
into Veiculos values ("74 XS 81","Bonneville","Pontiac");
into Veiculos values ("69 HC 72","Insight","Honda");
into Veiculos values ("54 LO 77","Laser","Plymouth");
into Veiculos values ("38 CH 92","Sierra 3500HD","GMC");
into Veiculos values ("31 NH 32","Nubira","Daewoo");
into Veiculos values ("68 UO 24","Caliber","Dodge");
into Veiculos values ("97 GR 75","Silverado Hybrid","Chevrolet");

-- Criar Modelos carros
into Modelos values ('Nubira', 'Daewoo');
into Modelos values ('RS 6', 'Audi');
into Modelos values ('EXP', 'Ford');
into Modelos values ('Pajero', 'Mitsubishi');
into Modelos values ('Z4', 'BMW');
into Modelos values ('Transit Connect', 'Ford');
into Modelos values ('Corvette', 'Chevrolet');
into Modelos values ('GT-R', 'Nissan');
into Modelos values ('MX-3', 'Mazda');
into Modelos values ('HHR', 'Chevrolet');
into Modelos values ('Outback', 'Subaru');
into Modelos values ('Discovery', 'Land Rover');
into Modelos values ('Aveo', 'Chevrolet');
into Modelos values ('Crown Victoria', 'Ford');
into Modelos values ('MKS', 'Lincoln');
into Modelos values ('F350', 'Ford');
into Modelos values ('Bronco', 'Ford');
into Modelos values ('Caliber', 'Dodge');
into Modelos values ('RDX', 'Acura');
into Modelos values ('Neon', 'Dodge');
into Modelos values ('Laser', 'Plymouth');
into Modelos values ('rio', 'Volkswagen');
into Modelos values ('FJ Cruiser', 'Toyota');
into Modelos values ('Carens', 'Kia');
into Modelos values ('Navigator L', 'Lincoln');
into Modelos values ('599 GTB Fiorano', 'Ferrari');
into Modelos values ('9-4X', 'Saab');
into Modelos values ('Liberty', 'Jeep');
into Modelos values ('Town Car', 'Lincoln');
into Modelos values ('Interceptor', 'Jensen');
into Modelos values ('Sierra 3500HD', 'GMC');
into Modelos values ('Forester', 'Subaru');
into Modelos values ('Countryman', 'MINI');
into Modelos values ('Matrix', 'Toyota');
into Modelos values ('Q', 'Infiniti');
into Modelos values ('Villager', 'Mercury');
into Modelos values ('Ram Wagon B350', 'Dodge');
into Modelos values ('Insight', 'Honda');
into Modelos values ('C-Class', 'Mercedes-Benz');
into Modelos values ('Integra', 'Acura');
into Modelos values ('Grand Cherokee', 'Jeep');
into Modelos values ('Silverado Hybrid', 'Chevrolet');
into Modelos values ('Bonneville', 'Pontiac');
into Modelos values ('Escalade EXT', 'Cadillac');
into Modelos values ('GS', 'Lexus');
into Modelos values ('Grand Am', 'Pontiac');
into Modelos values ('MKX', 'Lincoln');
into Modelos values ('Concorde', 'Chrysler');
into Modelos values ('Yukon', 'GMC');
into Modelos values ('Corrado', 'Volkswagen');


--Add motas
into Motas values ('08 TH 15');
into Motas values ('73 NO 55');
into Motas values ('27 DG 74');
into Motas values ('34 YW 21');
into Motas values ('55 QY 10');
into Motas values ('47 LE 79');
into Motas values ('24 GP 89');
into Motas values ('48 HT 93');
into Motas values ('56 LV 63');
into Motas values ('98 HV 29');
into Motas values ('31 AC 32');
into Motas values ('34 QX 88');
into Motas values ('90 DW 27');
into Motas values ('31 KM 99');
into Motas values ('18 YF 79');
into Motas values ('87 YS 91');
into Motas values ('68 BV 36');
into Motas values ('71 SS 33');
into Motas values ('75 OP 13');
into Motas values ('48 XC 57');
into Motas values ('34 TQ 59');
into Motas values ('02 KT 19');
into Motas values ('04 IH 76');
into Motas values ('83 CK 27');
into Motas values ('57 AG 09');
into Motas values ('14 EH 98');
into Motas values ('73 VJ 95');
into Motas values ('77 OH 96');
into Motas values ('79 DS 17');
into Motas values ('32 GZ 44');
into Motas values ('23 XP 11');
into Motas values ('44 JV 18');
into Motas values ('90 AS 70');
into Motas values ('84 OV 33');
into Motas values ('25 EG 13');
into Motas values ('68 EC 30');
into Motas values ('52 ZG 76');
into Motas values ('28 HA 03');
into Motas values ('23 OE 68');
into Motas values ('73 EK 78');
into Motas values ('32 FE 46');
into Motas values ('31 GH 97');
into Motas values ('02 UG 92');
into Motas values ('27 ZM 60');
into Motas values ('77 FO 18');
into Motas values ('39 SR 11');
into Motas values ('32 IA 28');
into Motas values ('46 ZS 00');
into Motas values ('48 NT 45');
into Motas values ('60 ZY 17');
into Motas values ('32 KI 49');
into Motas values ('38 MR 24');
into Motas values ('24 XS 55');
into Motas values ('14 FS 37');
into Motas values ('80 GS 44');
into Motas values ('96 WK 94');
into Motas values ('96 GB 74');
into Motas values ('95 EN 75');
into Motas values ('12 SC 10');
into Motas values ('42 GG 76');
into Motas values ('08 IU 05');
into Motas values ('84 AZ 21');
into Motas values ('17 XX 20');
into Motas values ('96 JP 73');
into Motas values ('63 ZD 20');
into Motas values ('31 YZ 55');
into Motas values ('56 PM 20');
into Motas values ('17 DE 95');
into Motas values ('56 TG 81');
into Motas values ('90 FX 51');
into Motas values ('60 UF 59');
into Motas values ('91 CI 51');
into Motas values ('09 SL 55');
into Motas values ('30 KY 08');
into Motas values ('18 ND 03');
into Motas values ('32 AS 29');
into Motas values ('22 FL 67');
into Motas values ('46 ZQ 73');
into Motas values ('28 KN 61');
into Motas values ('36 OJ 24');
into Motas values ('19 IU 39');
into Motas values ('01 QS 69');
into Motas values ('03 XD 20');
into Motas values ('65 OW 17');
into Motas values ('41 UZ 90');
into Motas values ('20 SA 95');
into Motas values ('15 GD 21');
into Motas values ('53 GY 47');
into Motas values ('21 FI 05');
into Motas values ('82 WS 56');
into Motas values ('92 WJ 85');
into Motas values ('19 TF 75');
into Motas values ('08 XT 97');
into Motas values ('95 BT 73');
into Motas values ('55 HZ 65');
into Motas values ('24 HI 16');
into Motas values ('74 NL 87');
into Motas values ('35 EI 85');
into Motas values ('02 RL 29');
into Motas values ('59 WN 86');
